-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM
    (
        SELECT ONLINE_SALE_ID ID, USER_ID USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
        FROM ONLINE_SALE 
        WHERE TO_CHAR(SALES_DATE, 'YYYYMMDD') LIKE '202203%'
        UNION 
        SELECT OFFLINE_SALE_ID, NULL, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
        FROM OFFLINE_SALE 
        WHERE TO_CHAR(SALES_DATE, 'YYYYMMDD') LIKE '202203%'
    )
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID