-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS 
WHERE ANIMAL_ID NOT IN
    ( SELECT A.ANIMAL_ID
        FROM ANIMAL_INS A, ANIMAL_OUTS B
        WHERE A.ANIMAL_ID = B.ANIMAL_ID)
ORDER BY ANIMAL_ID