
SELECT BB.FLAVOR
FROM (
SELECT B.FLAVOR, B.AA + A.TOTAL_ORDER
FROM FIRST_HALF A, (
SELECT FLAVOR, SUM(TOTAL_ORDER) AA
FROM JULY
GROUP BY FLAVOR) B
WHERE A.FLAVOR = B.FLAVOR
ORDER BY B.AA + A.TOTAL_ORDER DESC)BB
WHERE ROWNUM <= 3