-- 코드를 입력하세요
SELECT  A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE A, ONLINE_SALE B
WHERE A.ONLINE_SALE_ID = B.ONLINE_SALE_ID
GROUP BY A.USER_ID, A.PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY A.USER_ID, A.PRODUCT_ID DESC