-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM (
        SELECT *
        FROM BOOK_SALES 
        WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
    ) B, BOOK A
WHERE A.BOOK_ID = B.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY